---
# Codacy Configuration File
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Exclude patterns - files and directories to ignore
exclude_paths:
  # Git and GitHub directories
  - '.git/**'
  - '.github/**'

  # Test and spec directories (if not needed for analysis)
  - '.specify/**'
  - 'specs/**'
  - 'test/**'
  - 'Tests/**'

  # Build output directories
  - 'bin/**'
  - 'obj/**'
  - 'coverage/**'

  # Dependencies and packages
  - 'models/**'
  - 'addons/**'

  # Documentation and markdown files
  - 'docs/**'
  - '*.md'

  # YAML configuration files
  - 'yaml/**'
  - '*.yml'
  - '*.yaml'

  # Asset files
  - '*.png'
  - '*.jpg'
  - '*.jpeg'
  - '*.gif'
  - '*.mp3'
  - '*.wav'
  - '*.ogg'
  - '*.tres'
  - '*.tscn'
  - '*.import'
  - '*.uid'

  # Generated or temporary files
  - '*.csproj.old'
  - 'Copilot-Processing.md'
  - 'build_output.txt'

# Engine configuration
engines:
  # Enable StyleCop analyzer
  stylecop:
    enabled: true

  # Enable Roslyn analyzers for C#
  roslyn:
    enabled: true

# Code quality patterns to enforce
quality:
  # Require minimum code coverage
  coverage:
    minimum: 80

  # Complexity limits to maintain readability
  complexity:
    max: 15

  # Duplication detection
  duplication:
    max: 10

# Enhanced Roslyn analyzer rules for exception handling
roslyn:
  rules:
    # Critical: Ensure proper exception handling
    - id: "CA1031"
      severity: "error"  # Do not catch general exception types
    - id: "CA1062"
      severity: "error"  # Validate arguments of public methods
    - id: "CA2200"
      severity: "warning" # Rethrow to preserve stack details
    - id: "CA2201"
      severity: "warning" # Exception type not sufficiently specific

    # Critical: Null reference prevention
    - id: "CA2013"
      severity: "error"  # Do not use ReferenceEquals with value types
    - id: "CA2014"
      severity: "warning" # Do not use stackalloc in loops

    # Enhanced async/await handling
    - id: "CA2007"
      severity: "warning" # Consider calling ConfigureAwait on the awaited task
    - id: "CA2008"
      severity: "error"   # Do not create tasks without passing a TaskScheduler

    # Resource management
    - id: "CA2000"
      severity: "error"   # Dispose objects before losing scope

    # Security and reliability
    - id: "CA2100"
      severity: "error"   # Review SQL queries for security vulnerabilities
    - id: "CA2109"
      severity: "error"   # Review visible event handlers

# Enhanced StyleCop rules for code quality
stylecop:
  rules:
    # Exception handling documentation
    - id: "SA1613"
      severity: "error"  # Element parameter documentation must declare that parameter is not null
    - id: "SA1614"
      severity: "error"  # Element return value documentation must declare that return value is not null
    - id: "SA1620"
      severity: "warning" # Generic type parameter documentation must declare that parameter is not null
