repos:
  # Code formatting with dotnet-format (temporarily disabled due to existing formatting issues)
  # TODO: Fix all formatting issues and re-enable
  # - repo: local
  #   hooks:
  #     - id: dotnet-format
  #       name: "dotnet format"
  #       description: "Run dotnet format to ensure consistent code formatting"
  #       entry: dotnet
  #       args: ["format", "chapter-zero.csproj", "--verify-no-changes"]
  #       language: system
  #       pass_filenames: false
  #       files: \.(cs|csproj|sln)$
  #       exclude: ^.*\.generated\.cs$

  # Static analysis and build verification
  - repo: local
    hooks:
      - id: dotnet-build-warnaserror
        name: "dotnet build (warnings as errors)"
        description: "Run dotnet build with warnings treated as errors for static analysis"
        entry: dotnet
        args: ["build", "--warnaserror", "--no-restore"]
        language: system
        pass_filenames: false
        files: \.(cs|csproj|sln)$
        types: []

  # Unit tests (temporarily disabled while fixing broken tests)
  # TODO: Re-enable once all tests pass
  # - repo: local
  #   hooks:
  #     - id: dotnet-test
  #       name: "dotnet test"
  #       description: "Run unit tests to ensure code quality"
  #       entry: dotnet
  #       args: ["test", "--no-build", "--verbosity", "quiet"]
  #       language: system
  #       pass_filenames: false
  #       files: \.(cs|csproj|sln)$
  #       types: []

  # Security scanning (optional - can be enabled per developer)
  # - repo: local
  #   hooks:
  #     - id: trivy-security-scan
  #       name: "trivy security scan"
  #       description: "Run Trivy security scan for high and critical vulnerabilities"
  #       entry: trivy
  #       args: ["fs", "--exit-code", "1", "--severity", "HIGH,CRITICAL", "."]
  #       language: system
  #       pass_filenames: false
  #       files: .*
  #       types: []

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(tscn|tres|godot|import)$
      - id: end-of-file-fixer
        exclude: \.(tscn|tres|godot|import)$
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: \.(tscn|tres|godot|import)$

  # C# specific checks with Roslynator (requires separate installation)
  # TODO: Install Roslynator CLI tool and re-enable
  # - repo: local
  #   hooks:
  #     - id: roslynator-analyze
  #       name: "roslynator analyze"
  #       description: "Run Roslynator static analysis"
  #       entry: dotnet
  #       args: ["roslynator", "analyze", "--severity-level", "warning"]
  #       language: system
  #       pass_filenames: false
  #       files: \.(cs|csproj)$
  #       types: []