repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: ^(addons/yaml/examples/data/.*\.yaml|\.godot/.*)$
      - id: end-of-file-fixer
        exclude: ^\.godot/.*$
      - id: trailing-whitespace
        exclude: ^\.godot/.*$
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: mixed-line-ending

  # .NET checks (all local hooks)
  - repo: local
    hooks:
      # Step 1: Format check
      - id: dotnet-format
        name: .NET Format Check
        entry: dotnet format chapter-zero.csproj
        args: ['--verify-no-changes', '--no-restore']
        language: system
        types: [c#]
        pass_filenames: false
        stages: [commit]

      # Step 2: Build with warnings as errors
      - id: dotnet-build
        name: .NET Build (Debug)
        entry: dotnet build chapter-zero.csproj
        args: ['--configuration', 'Debug', '--no-restore']
        language: system
        types: [c#]
        pass_filenames: false
        stages: [commit]

      # Step 3: Run tests
      - id: dotnet-test
        name: .NET Test Suite
        entry: dotnet test chapter-zero.csproj
        args: ['--no-build', '--configuration', 'Debug', '--verbosity', 'minimal']
        language: system
        types: [c#]
        pass_filenames: false
        stages: [commit]
