namespace OmegaSpiral.Source.Scripts.Domain.Models;

/// <summary>
/// Represents script data for narrative content.
/// </summary>
public class ScriptData
{
    /// <summary>
    /// Gets or sets the source of the script data.
    /// </summary>
    public TestScriptSource Source { get; set; }

    /// <summary>
    /// Gets or sets the content of the script.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the timestamp of when the script was created.
    /// </summary>
    public DateTime Timestamp { get; set; }

    /// <summary>
    /// Gets or sets the lines of the script.
    /// </summary>
    public List<string> Lines { get; set; } = new List<string>();

    /// <summary>
    /// Gets or sets a value indicating whether the script is complete.
    /// </summary>
    public bool IsComplete { get; set; } = true;

    /// <summary>
    /// Gets or sets the origin of the script data.
    /// </summary>
    public TestDataOrigin Origin { get; set; } = TestDataOrigin.RealGameplaySession;

    /// <summary>
    /// Gets or sets the reason for fallback if applicable.
    /// </summary>
    public string FallbackReason { get; set; } = string.Empty;
}

/// <summary>
/// Defines the source of script data.
/// </summary>
public enum TestScriptSource
{
    /// <summary>
    /// Script generated by LLM.
    /// </summary>
    LLMGenerated = 0,

    /// <summary>
    /// Fallback script.
    /// </summary>
    Fallback = 1,

    /// <summary>
    /// Fallback dataset script.
    /// </summary>
    FallbackDataset = 2
}

/// <summary>
/// Represents the origin of test data.
/// </summary>
public enum TestDataOrigin
{
    /// <summary>
    /// Data originated from a real gameplay session.
    /// </summary>
    RealGameplaySession = 0,

    /// <summary>
    /// Data was generated by an LLM.
    /// </summary>
    LLMGenerated = 1
}
